package Intermediate_nodes;

import Data.trans.Sender;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.ByteBuffer;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.channels.SocketChannel;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.constants.Constants;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;

public class Node1 extends javax.swing.JFrame {
private Client ChatClient;
private ReadThread myRead=new ReadThread();
private String ServerName;
String name="node3";
ServerSocket servsock;
 Socket sock;
    ResultSet rs1, rs2, rs, rs3, rs4 = null;
    PreparedStatement stat, stat1, stat2, stat3, stat4 = null;
 private Sender.server DataSender;
    /** Creates new form Node1 */
    public Node1() throws SQLException {
        initComponents();
        jLabel3.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Node 1");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Intermediate nodes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Node 1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Node ID: ");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Connect");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Incoming Data Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Send File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("i-Trust");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGap(0, 21, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 460, 400);

        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 340, 402, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image-a.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-22, -16, 2410, 440);

        setSize(new java.awt.Dimension(520, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String s=ServerName;
      try {
        jTextArea1.append(InetAddress.getLocalHost().toString());
        Client ChatClient=new Client();
       ChatClient.start();
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            IncomingDataDetails.datasend = jLabel3.getText();
            IncomingDataDetails.nodeName="Node1";
            IncomingDataDetails inObj = new IncomingDataDetails();
        }
        catch(Exception e)
                {
//                    JOptionPane.showMessageDialog(null, e);
        } 
//        catch (IOException ex) {
//            JOptionPane.showMessageDialog(null, "IOEXCEPTION");
//            Logger.getLogger(Node1.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "SQLEXCEPTION");
//        Logger.getLogger(Node1.class.getName()).log(Level.SEVERE, null, ex);
//    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/false_data","root","admin");
            PreparedStatement pre=con.prepareStatement("select * from node3");
             ResultSet re=pre.executeQuery();
            if(re.next())
            {
                 String m=""+re.getString("filepath");
                 String filesize=getfilesize(m);
        System.out.println("filesize = " +filesize+ " Mega Bytes[MB]");
        jLabel5.setText(""+filesize);
        PreparedStatement pre1=con.prepareStatement("update node3 set filesize='"+jLabel5.getText()+"'");
             int re3=pre1.executeUpdate();
            
            try{
            //    JOptionPane.showMessageDialog(null, "in passing ");
            PreparedStatement check=con.prepareStatement("select * from node3");
            ResultSet re2=check.executeQuery();
            if(re2.next())
            {
//                String name1=""+re.getString(name);
           //     JOptionPane.showMessageDialog(null, "I am in passing function");
                try{
                PreparedStatement check1=con.prepareStatement("insert into full ( filename, filepath, ip, filesize, source_name, passing) values ('"+re2.getString("filename")+"','d:\\\\\\\\"+re2.getString("filename")+"','"+re2.getString("ip")+"','"+re2.getString("filesize")+"','"+re2.getString("source_name")+"','node3')");
                int re1=check1.executeUpdate();
                if(re1>0)
                {
           //         JOptionPane.showMessageDialog(null, "values passed into full table");
                    System.out.println("Done");
                }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            
//            Class.forName("");
            
//           String file=jLabel3.getText();
//                        Retrivingfiles files = new Retrivingfiles(file);
//
//                        // Socket cli= new Socket("127.0.0.1",2222);
//                        Socket cli = new Socket(Constants.NodeOneIpAddress, 2222);
//
//                        System.out.println("Connection accepeted ...");
//                        System.out.println("access accepted ...");
//                        sdata();
//                      
//            

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "File Not Found");
            }
             }       } catch (Exception e) {
                        System.out.println(e);
                    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {     
        MisDetect_intermediatenodes.nodename="Node1";
        MisDetect_intermediatenodes s=new MisDetect_intermediatenodes();
        s.show();
        String action="Performing SACK";
            String nname="Node1";
            new logdetails(nname,action);
    } catch (SQLException ex) {
        Logger.getLogger(Node1.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Node1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Node1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Node1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Node1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new Node1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Node1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private String getfilesize(String m) throws FileNotFoundException, IOException {
       
        File file=new File(m);
         BufferedReader reader=null;
         int charCount=0;
         int lineCount=0;
         int wordCount=0;
         String megabytes=null;
        if(!file.exists() || !file.isFile())
        {
            System.out.println("FileSize Doe's Not exist ");
            return null;
        }
        try
        {
             
            reader = new BufferedReader(new FileReader(m));
             
            String currentLine = reader.readLine();
             
            while (currentLine != null)
            {
                 
                lineCount++;
            
                String[] words = currentLine.split(" ");
                 
                //Updating the wordCount
                 
                wordCount = wordCount + words.length;
                 
                //Iterating each word
                 
                for (String word : words)
                {
                    //Updating the charCount
                     
                    charCount = charCount + word.length();
                }
                 
                //Reading next line into currentLine
                 
                currentLine = reader.readLine();
            }
             
            //Printing charCount, wordCount and lineCount
             
            System.out.println("Number Of Chars In A File : "+charCount);
            megabytes=""+charCount; 
            System.out.println("Number Of Words In A File : "+wordCount);
             
            System.out.println("Number Of Lines In A File : "+lineCount);
        } 
        catch (IOException e) 
        {
            e.printStackTrace();
        }
        finally
        {
            try
            {
                reader.close();           //Closing the reader
            }
            catch (IOException e) 
            {
                e.printStackTrace();
            }
        }
        
        
//        float bytes=file.length();
//        float kilobytes=(bytes/1024);
//        float megebytes=(kilobytes/1024);


        return megabytes;
        
    }
       public class Client extends Thread {
        private static final int PORT=9999;
        private LinkedList Clients;
        private ByteBuffer ReadBuffer;
        private ByteBuffer writeBuffer;
        private SocketChannel SChan;
        private Selector ReadSelector;
        private CharsetDecoder asciiDecoder;
        
        public Client() {
            Clients=new LinkedList();
            ReadBuffer=ByteBuffer.allocateDirect(300);
            writeBuffer=ByteBuffer.allocateDirect(300);
            asciiDecoder = Charset.forName( "US-ASCII").newDecoder();
        }
        
        public void run() {
        //    JOptionPane.showMessageDialog(null, "Run has been activated");
            ServerName=Constants.NodeOneHostName;
            System.out.println(ServerName);
            Connect(ServerName);
            myRead.start();
            while (true) {
                
                ReadMassage();
                
                try {
                    Thread.sleep(30);
                } catch (InterruptedException ie){
                }
            }
            
        }
        public void Connect(String hostname) {
            try {
               // ReadSelector = Selector.open();
                // JOptionPane.showMessageDialog(null, hostname);
//                InetAddress addr = InetAddress.getByName(hostname);
InetAddress addr=InetAddress.getLocalHost();

      //          JOptionPane.showMessageDialog(null, addr);
                SChan = SocketChannel.open(new InetSocketAddress(addr, PORT));
      //           JOptionPane.showMessageDialog(null, SChan);
                SChan.configureBlocking(false);
                
                SChan.register(ReadSelector, SelectionKey.OP_READ, new StringBuffer());
            }
            
            catch (Exception e) {
            }
        }
        public void SendMassage(String messg) {
            prepareBuffer(messg);
            channelWrite(SChan);
        }
        
        
        public void prepareBuffer(String massg) {
            writeBuffer.clear();
            writeBuffer.put(massg.getBytes());
            writeBuffer.putChar('\n');
            writeBuffer.flip();
        }
        
        public void channelWrite(SocketChannel client) {
            long num=0;
            long len=writeBuffer.remaining();
            while(num!=len) {
                try {
                    num+=SChan.write(writeBuffer);
                    
                    Thread.sleep(5);
                } catch (IOException ex) {
                    ex.printStackTrace();
                } catch(InterruptedException ex) {
                    
                }
                
            }
            writeBuffer.rewind();
        }
        
        public void ReadMassage() {
            
            try {
                
                ReadSelector.selectNow();
                
                Set readyKeys = ReadSelector.selectedKeys();
                
                Iterator i = readyKeys.iterator();
                
                while (i.hasNext()) {
                    
                    SelectionKey key = (SelectionKey) i.next();
                    i.remove();
                    SocketChannel channel = (SocketChannel) key.channel();
                    ReadBuffer.clear();
                    
                    
                    long nbytes = channel.read(ReadBuffer);
                    
                    if (nbytes == -1) {
                        jTextArea1.append("You logged out !\n");
                        channel.close();
                    } else {
                        
                        StringBuffer sb = (StringBuffer)key.attachment();
                        
                        ReadBuffer.flip( );
                        String str = asciiDecoder.decode( ReadBuffer).toString( );
                        sb.append( str );
                        ReadBuffer.clear( );
                        
                        String line = sb.toString();
                        
                        if ((line.indexOf("\n") != -1) || (line.indexOf("\r") != -1)) {
                            line = line.trim();
                            jTextArea1.setText("");
                            jTextArea1.append(line);
                            jTextArea1.append(""+'\n');
                            jLabel3.setText(line);
                            sb.delete(0,sb.length());
                        }
                    }
                }
            } catch (IOException ioe) {
            } catch (Exception e) {
            }
        }
    }
        class ReadThread extends Thread {
        public void run() {
            ChatClient.ReadMassage();
        }
    }
//          public void sdata() {
//        try {
//while (true) {
//
//                // sendfile
//    String file=jLabel3.getText();
//                File myFile = new File(file);
//                byte[] mybytearray = new byte[(int) myFile.length()];
//                FileInputStream fis = new FileInputStream(myFile);
//                BufferedInputStream bis = new BufferedInputStream(fis);
//                bis.read(mybytearray, 0, mybytearray.length);
//                OutputStream os = sock.getOutputStream();
//                System.out.println("Sending...");
//                JOptionPane.showMessageDialog(null, "Forwarding file is ".concat(file));
//                os.write(mybytearray, 0, mybytearray.length);
//                os.flush();
//                sock.close();
//                
//            }
//        } catch (Exception e) {
//          System.out.println(e);
//        }

//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
